### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by kichuman28** [Joeljaison391/Blogz-Backend#1]
![Screenshot 2024-06-22 115803](https://github.com/Joeljaison391/Blogz-Backend/assets/97717315/4d633a34-dbd6-46dd-be2e-9c2cd99e6607)

**Comment by HarisChandio** [comment]
Its a cors issue, basically only mentioned urls in .env files are allowed to hit the backend, so I have mentioend some more localhost urls in .env file
